# Config file for Goldeneye 007 US Recompilation

[input]
#entrypoint = 0x80000450
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
#relocatable_sections_path = "overlays.us.txt"
elf_path = "ge007.u.elf"
#symbols_file_path = "GE007RecompSyms/ge.us.syms.toml"
rom_file_path = "ge007.u.z64"

[patches]
stubs = [

]